// The built-in Sakura Drift, made from the game's own: X343's cherry petals.
//
//   npx esbuild tools/effects/sakura-drift.mts --bundle --platform=node --format=esm \
//     --tsconfig=tsconfig.json --outfile=/tmp/sakura.mjs && node /tmp/sakura.mjs <X343 stage .glb>
//
// The stage carries the game's petal systems (yinghua, seven of them over its
// path) as effects generated by lib/unity-particles.ts, each standing on point
// pairs the stage PMX places in its trees. A built-in has no stage, so this
// bakes those emitter frames into the effect, centred on the scene's origin,
// and gives every emitter the slowest system's rules (yinghua_1, ps11: three
// petals a second, 6–7 s each, drifting on light curl noise). The petal picture rides
// in the entry itself, as a data URI (lib/effect-textures.ts): the effect then
// goes wherever its entry goes, library or published scene, picture and all.
//
// Writes the entry into content/effects.json, in place of the old Sakura Drift
// (its id and name kept, so a scene that has it gets this one).
import { readFileSync, writeFileSync } from "node:fs"
import { readPmxDocument } from "reze-engine"
import { glbToStage } from "@/lib/gltf-stage"
import { particleEffectWgsl, type BakedEmitter, type ParticleClass } from "@/lib/unity-particles"

const glbPath = process.argv[2]
if (!glbPath) throw new Error("usage: node sakura.mjs <X343 stage .glb>")
const bytes = readFileSync(glbPath)
const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer

// the game's particle classes, as the stage file carries them
const jsonLength = new DataView(buffer).getUint32(12, true)
const gltf = JSON.parse(new TextDecoder().decode(new Uint8Array(buffer, 20, jsonLength)))
type Entry = ParticleClass & { prefix: string; textures?: ({ png?: string; srgb?: boolean } | null)[] }
const classes = JSON.parse(gltf.scenes[0].extras.reze.particlesJson) as Entry[]
const petals = classes.filter((c) => c.name.startsWith("yinghua"))
if (!petals.length) throw new Error("no yinghua particle systems in this stage: is it X343?")
// THE SLOW DRIFTERS' RULES. X343's seven systems are not alike: three brisk
// (1–1.5 game units a second, ten petals a second on the busiest), two medium,
// two slow (0.5–0.9, light noise, 6–7 s lives). Every spawner on the brisk rules
// fell twice as fast and twice as thick as the whole shrine; around a cast the
// slow ones are what the game hangs near the camera.
const meanSpeed = (c: Entry) => (c.spec.speed.lo + c.spec.speed.hi) / 2
const base = petals.reduce((a, c) => (meanSpeed(c) < meanSpeed(a) || (meanSpeed(c) === meanSpeed(a) && c.spec.lifetime.hi > a.spec.lifetime.hi) ? c : a))

// the emitter points, as the importer places them: bones named ps<k>_NNN, a pair per emitter
const stage = glbToStage(buffer, glbPath.replace(/\\/g, "/"))
const pmx = stage.files.find((f) => f.path === stage.pmxPath)!
const pmxBytes = pmx.bytes as Uint8Array
const doc = readPmxDocument(pmxBytes.buffer.slice(pmxBytes.byteOffset, pmxBytes.byteOffset + pmxBytes.byteLength) as ArrayBuffer)
const frames: BakedEmitter[] = []
for (const c of petals) {
  const bones = doc.bones.filter((b) => b.name.startsWith(c.prefix)).sort((a, b) => a.name.localeCompare(b.name))
  for (let i = 0; i + 1 < bones.length; i += 2) {
    const z = bones[i]
    const x = bones[i + 1]
    frames.push({ o: [...z.position], z: [...z.tailPosition!], x: [...x.tailPosition!] })
  }
}
// AROUND THE CAST, not where X343 put them. Its spawners hang over the two ends
// of its path, 600 units apart, and centred on their mean they left the origin
// (where a scene stands its cast) in the empty middle. Each keeps its own frame
// and the canopy height they share; they stand on two staggered rings, four
// close and four wide, so petals cross the shot and fall behind and beside her.
//
// AND PETALS AT AN MMD SHOT'S SIZE: the game's camera stands at arm's length,
// so its 1–4.5 cm petals read; an MMD shot frames a whole body from far further.
// The petals alone grow PETAL times. Not the spawners: scaling an emitter scales
// its particles' speed and spread with it, and the fall turned twice as fast
// as the game's.
const PETAL = 1
const RINGS = [8, 22]
// AND OVER A WHOLE SCENE, as Snow, Rain and Ember Drift fill theirs. The game
// pours its petals from small discs over its path; a built-in has no path to
// follow, so each spawner's disc is widened AREA times (the emitter's SHAPE
// scale, which spreads where petals start and nothing else) and pours DENSITY
// times as many, so the air stays as thick as the game's over the larger
// area. Their speed, size, spin and swirl stay exactly the game's.
const AREA = 6
const DENSITY = 8
const height = frames.reduce((s, e) => s + e.o[1], 0) / frames.length
const round = (v: number) => Math.round(v * 1000) / 1000
frames.forEach((e, i) => {
  const ring = RINGS[i % RINGS.length]
  const angle = ((i + (i % 2) * 0.5) / frames.length) * 2 * Math.PI
  e.o = [round(Math.cos(angle) * ring), round(height), round(Math.sin(angle) * ring)]
  e.z = e.z.map(round) as BakedEmitter["z"]
  e.x = e.x.map((v) => round(v * AREA)) as BakedEmitter["x"]
})
const rate = base.spec.emission.rate
const spec = { ...base.spec, max: base.spec.max * DENSITY, emission: { ...base.spec.emission, rate: { ...rate, lo: rate.lo * DENSITY, hi: rate.hi * DENSITY } } }

const world = (base.metresPerUnit ?? 0.64) * 12.5
const wgsl = particleEffectWgsl({ ...base, spec, emitters: frames.length }, world, frames, PETAL)
const textures = (base.textures ?? []).map((t) => (t?.png ? { url: `data:image/png;base64,${t.png}`, srgb: t.srgb !== false } : null))

const path = "content/effects.json"
const effects = JSON.parse(readFileSync(path, "utf8")) as { name: string; description: string; tags: string[]; payload: Record<string, unknown> }[]
const entry = effects.find((e) => e.name === "Sakura Drift")
if (!entry) throw new Error("no Sakura Drift in content/effects.json")
entry.description =
  "Cherry petals from Aether Gazer's X343 shrine, drawn by the game's own particle rules and petal picture: " +
  `${frames.length} wide spawners over the scene, each petal swirling down on curl noise for six or seven seconds.`
entry.payload = { wgsl, textures }
writeFileSync(path, JSON.stringify(effects, null, 1) + "\n")
console.log(`Sakura Drift: ${frames.length} emitters from ${petals.length} systems (rules of ${base.name}), ${wgsl.length} chars of WGSL, ${textures.filter(Boolean).length} picture(s)`)
