// The shot, written out as an After Effects script.
//
// A .jsx AE runs to build a composition holding the camera the video was
// rendered with, plus a null per character, keyed frame for frame. What it is
// for: taking a finished render into AE and having the 3D space still be there
// — put a flare where her hand was, a title that sits behind her, a light that
// tracks the shot — without any of it drifting.
//
// THE RIG IS NOT INVENTED HERE. It is the one MMD2AE has produced for a decade,
// down to the layer names, because AE projects and muscle memory are built
// around it: two nulls and a camera, parented Y → X → camera.
//
//   layNully.position      the point the shot orbits
//   layNully.yRotation     yaw
//   layNullx.xRotation     pitch
//   layNullx.zRotation     roll
//   layNullx.anchorPoint.z HOW FAR BACK
//   layCam.zoom            the lens
//
// Distance as the child null's ANCHOR POINT is the piece worth understanding:
// an anchor offset is applied after that null's rotations, so it pushes the
// camera back along its own axis — which is exactly what an MMD camera distance
// means. Nothing is composed into a matrix, so every channel stays separately
// keyable in AE, and an animator can grab the yaw without touching the rest.
//
// THE SAMPLES COME FROM THE RENDER, not from re-reading the camera VMD. The
// export loop advances the engine one exact frame at a time and reads the pose
// inside that loop, so whatever actually drove the shot — a camera clip, an
// orbit, a follow, a framing override — is what lands in the script. A second
// pass over the VMD would be a second opinion, and the two would part company
// the first time anything but the clip moved the camera.

/** One rendered frame's shot, in MMD's own terms. */
export type ShotSample = {
  /** The point the camera orbits, in MMD units. */
  target: [number, number, number]
  /** Euler radians: pitch, yaw, roll. */
  rotation: [number, number, number]
  /** Negative — the camera sits behind its target, as a VMD states it. */
  distance: number
  /** Vertical field of view, radians. */
  fov: number
}

/** One character's place at one frame. */
export type CastSample = {
  position: [number, number, number]
  /** Euler radians, applied in AE's own order (see rotation notes below). */
  rotation: [number, number, number]
}

export type AeScriptInput = {
  /** Exactly the video's — the comp is built from these, so it lines up by
   *  construction rather than by the person remembering to match them. */
  width: number
  height: number
  fps: number
  /** Frames actually written. Duration follows from it and the rate. */
  frames: number
  /** Where in the clip the render started, seconds. The comp starts at zero
   *  either way; this only names the file. */
  startTime: number
  camera: ShotSample[]
  /** A null per character, each with one sample per frame. */
  cast: { name: string; samples: CastSample[] }[]
  /**
   * MMD units to AE pixels.
   *
   * A free parameter: scale the camera and everything it looks at by the same
   * number and the projection is identical, because the lens is set from the
   * comp's own height rather than from the world. It matters only when AE 3D
   * layers of your own have to sit alongside — then it decides how big a metre
   * is. The old tool exposes the same dial for the same reason.
   */
  scale: number
}

const DEG = 180 / Math.PI
/** AE writes times in seconds, and a keyframe landing a hair off its frame is a
 *  keyframe AE may snap somewhere else. Eight places is what the reference uses. */
const t = (n: number) => n.toFixed(8)
const f = (n: number) => (Object.is(n, -0) ? 0 : n).toFixed(3)

/**
 * The lens, as AE states it.
 *
 * AE has no field-of-view field: zoom is the distance in PIXELS from the camera
 * to the comp plane, so the same shot is a different number on a different comp
 * height. Deriving it from the comp we are about to create is what keeps the
 * two agreeing.
 */
const zoomFor = (fov: number, height: number) => height / (2 * Math.tan(fov / 2))

/**
 * Write the script.
 *
 * One string, no I/O — so it can be tested against a known shot without a
 * browser, an engine or a file system.
 */
export function aeScript(input: AeScriptInput): string {
  const { width, height, fps, frames, camera, cast, scale } = input
  const duration = frames / fps
  const out: string[] = []
  const w = (s: string) => out.push(s)

  w("// Generated by reze-design — the camera and cast of an exported render.")
  w("//")
  w(`// ${width}x${height} @ ${fps}fps, ${frames} frames (${duration.toFixed(3)}s)`)
  w(`// MMD units x ${scale} = AE pixels.`)
  w("//")
  w("// Run it from File > Scripts > Run Script File. It builds its own comp, so")
  w("// nothing in your project is touched.")
  w("")
  w(`var Width       = ${width};`)
  w(`var Height      = ${height};`)
  w("var AspectRatio = 1.0;")
  w(`var Duration    = ${duration.toFixed(6)};`)
  w(`var FPS         = ${fps};`)
  w("")
  w("app.beginUndoGroup(\"reze-design camera\");")
  w("")
  w('var newComp  = app.project.items.addComp( "MMD CAMERA", Width, Height, AspectRatio, Duration, FPS );')
  w('var layCam   = newComp.layers.addCamera( "MMD CAMERA", [ 0, 0 ] );')
  w("var layNullx = newComp.layers.addNull();")
  w("var layNully = newComp.layers.addNull();")
  w("")
  w('layNully.name        = "MMD CAMERA CONTROL Y";')
  w("layNully.threeDLayer = true;")
  w("layNully.anchorPoint.setValue( [ 0.0, 0.0, 0.0 ] );")
  w("layNully.position.setValue( [ 0.0, 0.0, 0.0 ] );")
  w("")
  w("layNullx.parent      = layNully;")
  w('layNullx.name        = "MMD CAMERA CONTROL X";')
  w("layNullx.threeDLayer = true;")
  w("layNullx.anchorPoint.setValue( [ 0.0, 0.0, 0.0 ] );")
  w("layNullx.position.setValue( [ 0.0, 0.0, 0.0 ] );")
  w("")
  w("layCam.parent = layNullx;")
  w("layCam.anchorPoint.setValue( [ 0.0, 0.0, 0.0 ] );")
  w("layCam.position.setValue( [ 0.0, 0.0, 0.0 ] );")
  if (camera.length) w(`layCam.property( "zoom" ).setValue( ${f(zoomFor(camera[0].fov, height))} );`)
  w("")

  camera.forEach((s, i) => {
    const time = t(i / fps)
    // Y IS FLIPPED. AE's y axis points down the screen and MMD's points up, and
    // this is the one place the two spaces disagree — get it wrong and the shot
    // is upside down in a way that looks like a rotation bug.
    w(
      `layNully.position.setValueAtTime( ${time}, [ ${f(s.target[0] * scale)}, ${f(-s.target[1] * scale)}, ${f(
        s.target[2] * scale,
      )} ] );`,
    )
    w(`layNully.position.setSpatialAutoBezierAtKey( ${i + 1}, false );`)
    // Yaw is negated with it: flipping one axis reverses the handedness, and a
    // rotation about the flipped axis has to reverse to match.
    w(`layNully.yRotation.setValueAtTime( ${time}, ${f(-s.rotation[1] * DEG)} );`)
    w(`layNullx.anchorPoint.setValueAtTime( ${time},[ 0.0, 0.0, ${f(s.distance * scale)} ] );`)
    w(`layNullx.anchorPoint.setSpatialAutoBezierAtKey( ${i + 1}, false );`)
    w(`layNullx.xRotation.setValueAtTime( ${time}, ${f(s.rotation[0] * DEG)} );`)
    w(`layNullx.zRotation.setValueAtTime( ${time}, ${f(s.rotation[2] * DEG)} );`)
    // KEYED EVERY FRAME, not set once. A shot whose lens never moves writes the
    // same number all the way through, which costs a few kilobytes; a shot that
    // zooms and was written once is simply wrong, and nothing in AE would say so.
    w(`layCam.property( "zoom" ).setValueAtTime( ${time}, ${f(zoomFor(s.fov, height))} );`)
  })

  cast.forEach((member, n) => {
    const v = `layCast${n}`
    w("")
    w(`var ${v} = newComp.layers.addNull();`)
    w(`${v}.name        = ${JSON.stringify(member.name)};`)
    w(`${v}.threeDLayer = true;`)
    w(`${v}.anchorPoint.setValue( [ 0.0, 0.0, 0.0 ] );`)
    member.samples.forEach((s, i) => {
      const time = t(i / fps)
      w(
        `${v}.position.setValueAtTime( ${time}, [ ${f(s.position[0] * scale)}, ${f(-s.position[1] * scale)}, ${f(
          s.position[2] * scale,
        )} ] );`,
      )
      w(`${v}.position.setSpatialAutoBezierAtKey( ${i + 1}, false );`)
      // AE takes orientation as [x, y, z] degrees. Same two flips as the camera,
      // for the same reason.
      w(
        `${v}.orientation.setValueAtTime( ${time}, [ ${f(s.rotation[0] * DEG)}, ${f(-s.rotation[1] * DEG)}, ${f(
          s.rotation[2] * DEG,
        )} ] );`,
      )
    })
  })

  w("")
  w("app.endUndoGroup();")
  w("")
  return out.join("\n")
}
