// Build the AI's authoring guides from the user manual.
//
//   node scripts/agent-guides.mjs          write lib/ai/authoring-guides.ts
//   node scripts/agent-guides.mjs --check  exit 1 if it is out of date
//
// The AI reads how to write an effect or a shader graph from the same pages a
// person does — the manual's §2.3 (effects), §2.4 (graphs) and Appendix D (the
// node reference) — so there is one source of truth and nothing to keep in
// step by hand. The guides are a generated module rather than a file read at
// run time because the tools run in the browser, where docs/ does not exist.
// Run it after editing those sections; the --check form is in the test suite.

import { readFileSync, writeFileSync } from "node:fs"

const manual = readFileSync("docs/manual/en.md", "utf8").split(/\r?\n/)

/** Lines from the heading that starts with `from` up to (not including) the
 *  next heading that starts with `to`. */
function section(from, to) {
  const start = manual.findIndex((l) => l.startsWith(from))
  if (start < 0) throw new Error(`no heading "${from}" in docs/manual/en.md`)
  const rel = manual.slice(start + 1).findIndex((l) => to.some((t) => l.startsWith(t)))
  const end = rel < 0 ? manual.length : start + 1 + rel
  return manual.slice(start, end).join("\n").trim()
}

const effects = section("## 2.3 ", ["## 2.4 "])
const graphs = [section("## 2.4 ", ["## 2.5 "]), section("# Appendix D", ["# Appendix E"])].join("\n\n")

const out = `// GENERATED by scripts/agent-guides.mjs from docs/manual/en.md — do not edit.
// The AI's guides to writing effects and shader graphs (read_authoring_guide).

export const EFFECTS_GUIDE = ${JSON.stringify(effects)}

export const GRAPHS_GUIDE = ${JSON.stringify(graphs)}
`

const target = "lib/ai/authoring-guides.ts"
if (process.argv.includes("--check")) {
  const now = readFileSync(target, "utf8")
  if (now !== out) {
    console.error(`${target} is out of date with docs/manual/en.md — run: node scripts/agent-guides.mjs`)
    process.exit(1)
  }
  console.log(`${target} is up to date`)
} else {
  writeFileSync(target, out)
  console.log(`wrote ${target}: effects ${effects.length} chars, graphs ${graphs.length} chars`)
}
